name: CI

on:
  push:
    branches: [main]
  pull_request:
  workflow_dispatch:

jobs:
  go-build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: "1.16"
      - run: go test -v --race -coverprofile=coverage.txt -covermode=atomic ./...
      - run: go build -o server cmd/server/main.go
      - run: go build -o client cmd/client/main.go
      - run: bash <(curl -s https://codecov.io/bash)
