name: Setup
on: push

jobs:
  setup:
    if: (github.event.commits[0].message == 'Initial commit') && (github.run_number == 1)
    runs-on: ubuntu-latest
    steps:
    - name: Set up Python
      uses: actions/setup-python@v1
      with:
        python-version: 3.6
        
    - name: Copy Repository Contents
      uses: actions/checkout@v2
      
    - name: modify files
      run: |
        import re, os
        from pathlib import Path
        from configparser import ConfigParser

        nwo = os.getenv('GITHUB_REPOSITORY')
        username, repo_name = nwo.split('/')
        
        readme_path = Path('README.md')
        readme = readme_path.read_text().replace('server-client-go', repo_name)
        readme_path.write_text(readme)
      shell: python
      
    - name: commit changes
      run: |
        git config --global user.email "${GH_EMAIL}"
        git config --global user.name "${GH_USERNAME}"
        git checkout -B automated-setup
        git rm .github/workflows/setup.yml
        git add README.md
        git commit -m'setup repo'
        git push -f --set-upstream origin automated-setup
      env: 
        GH_EMAIL: ${{ github.event.commits[0].author.email }}
        GH_USERNAME: ${{ github.event.commits[0].author.username }}

    - name: Open a PR
      uses: actions/github-script@0.5.0
      with:
        github-token: ${{secrets.GITHUB_TOKEN}}
        script: |
          var fs = require('fs');
          var contents = "your initial PR";
          github.pulls.create({
                        owner: context.repo.owner,
                        repo: context.repo.repo,
                        title: 'Initial Setup',
                        head: 'automated-setup',
                        base: 'master',
                        body: `${contents}`
                        })
# reference: https://github.com/fastai/fastpages/blob/bf5669e698d1e3827dd919d2662d3f5ae565d1cc/.github/workflows/setup.yaml
